name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    types: [ opened, synchronize ]
    branches: [ main ]
  workflow_dispatch:
  schedule:
    - cron: '55 17 * * *'

jobs:
  quality:
    uses: prinsfrank/CI-PHP/.github/workflows/quality.yml@d6f1253ff160f53f17135ff21e12d760318c7d5c
    with:
      PHP_VERSION: '8.3'
    secrets: inherit
