name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    types: [ opened, synchronize ]
    branches: [ main ]

jobs:
  quality:
    uses: prinsfrank/CI-PHP/.github/workflows/quality.yml@main
    with:
      PHP_VERSION: '8.3'
    secrets:
      GH_TOKEN: ${{ github.token }}
